apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.16.1
        name: nginx
        envFrom:
        - secretRef:
            name: mysecret
        envFrom:
        - configMapRef:
            name: db
      tolerations:
      - key: Assignment
        operator: Exists
        effect: NoSchedule
status: {}
